pipeline {
    triggers {
        githubPush()
    }
    agent any

    stages {
        stage('Test') {
            steps {
                echo 'Triggered successfully!'
            }
        }
    }
}
